######################################################################
# Automatically generated by qmake (2.01a) Sat Jun 5 06:07:15 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += lab2.h
SOURCES += lab2.cpp
